const topbarKeywords = {
    settings:[
        {
            settingName:'基础颜色',
            defaultColor:'topbarBaseColor',
            changeMethod:'changeTopbarBaseColor',
        },
        {
            settingName:'默认背景',
            defaultColor:'topbarBgcolor',
            changeMethod:'changeTopbarBgcolor',
        },
        {
            settingName:'默认文字',
            defaultColor:'topbarColor',
            changeMethod:'changeTopbarColor',
        },
        {
            settingName:'默认标题',
            defaultColor:'topbarTitleSpanColor',
            changeMethod:'changeTopbarTitleSpanColor',
        },
        {
            settingName:'默认分割线',
            defaultColor:'topbarFengeColor',
            changeMethod:'changeTopbarFengeColor',
        },
        {
            settingName:'滑过文字',
            defaultColor:'topbarHoverColor',
            changeMethod:'changeTopbarHoverColor',
        },
        {
            settingName:'滑过背景',
            defaultColor:'topbarHoverBgcolor',
            changeMethod:'changeTopbarHoverBgcolor',
        },
        {
            settingName:'活动文字',
            defaultColor:'topbarActiveColor',
            changeMethod:'changeTopbarActiveColor',
        },
        {
            settingName:'活动背景',
            defaultColor:'topbarActiveBgcolor',
            changeMethod:'changeTopbarActiveBgcolor',
        },
        {
            settingName:'搜索框文字',
            defaultColor:'topbarInputSearchColor',
            changeMethod:'changeTopbarInputSearchColor',
        },
        {
            settingName:'搜索框背景',
            defaultColor:'topbarInputSearchBg',
            changeMethod:'changeTopbarInputSearchBg',
        },
        {
            settingName:'搜索框滑过文字',
            defaultColor:'topbarInputSearchHoverColor',
            changeMethod:'changeTopbarInputSearchHoverColor',
        },
        {
            settingName:'搜索框滑过背景',
            defaultColor:'topbarInputSearchHoverBg',
            changeMethod:'changeTopbarInputSearchHoverBg',
        },
        {
            settingName:'搜索框图标',
            defaultColor:'topbarInputSearchIconColor',
            changeMethod:'changeTopbarInputSearchIconColor',
        },
        {
            settingName:'菜单项文字',
            defaultColor:'topbarMenuItemColor',
            changeMethod:'changeTopbarMenuItemColor',
        },
        {
            settingName:'菜单项滑过文字',
            defaultColor:'topbarMenuItemHoverColor',
            changeMethod:'changeTopbarMenuItemHoverColor',
        },
        {
            settingName:'菜单项活动文字',
            defaultColor:'topbarMenuItemActiveColor',
            changeMethod:'changeTopbarMenuItemActiveColor',
        },
        {
            settingName:'下拉选择框文字',
            defaultColor:'topbarSelectdownColor',
            changeMethod:'changeTopbarSelectdownColor',
        },
        {
            settingName:'下拉选择框背景',
            defaultColor:'topbarSelectdownBgcolor',
            changeMethod:'changeTopbarSelectdownBgcolor',
        },
        {
            settingName:'下拉选择框滑过背景',
            defaultColor:'topbarSelectdownHoverBgcolor',
            changeMethod:'changeTopbarSelectdownHoverBgcolor',
        },
        {
            settingName:'下拉菜单项滑过文字',
            defaultColor:'topbarSelectdownItemHoverColor',
            changeMethod:'changeTopbarSelectdownItemHoverColor',
        },
        {
            settingName:'下拉菜单项滑过背景',
            defaultColor:'topbarSelectdownItemHoverBgcolor',
            changeMethod:'changeTopbarSelectdownItemHoverBgcolor',
        },
        {
            settingName:'人物图标',
            defaultColor:'topbarIconPerson',
            changeMethod:'changeTopbarIconPerson',
        },
        {
            settingName:'人物图标背景',
            defaultColor:'topbarIconPersonBg',
            changeMethod:'changeTopbarIconPersonBg',
        },
    ]
}
export default topbarKeywords